apiVersion: v1
kind: Service
metadata:
    name: "dockeryellow-ff01"
    labels:
        app: "dockeryellow-ff01"
spec:
    type: LoadBalancer
    ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
    selector:
        app: "dockeryellow-ff01"